---
title: "script-Yimin"
author: "Yimin Wang"
date: "2025-04-17"
output: html_document
---

```{r setup}
library(dplyr)
library(readxl)
library(broom)
library(ggplot2)
df <- read_excel("sample_600_coded_0416.xlsx")
colnames(df)[6:11] <- c("Vote", "Gameplay", "Story", "Sociability", "Scariness", "Sequel_Purchased")



clean_binary <- function(x) {
  x <- trimws(tolower(as.character(x))) 
  x[x %in% c("1", "yes", "y")] <- 1
  x[x %in% c("0", "no", "n")] <- 0
  x[!(x %in% c("0", "1"))] <- NA       
  return(as.numeric(x))                 
}

df <- df %>%
  mutate(
    Gameplay = clean_binary(Gameplay),
    Story = clean_binary(Story),
    Sociability = clean_binary(Sociability),
    Scariness = clean_binary(Scariness),
    Sequel_Purchased = clean_binary(Sequel_Purchased)
  )

df_clean <- df %>%
  filter(!is.na(Sequel_Purchased))

# SUM
df_clean <- df_clean %>% 
  mutate(Overall = Gameplay + Story + Sociability + Scariness)

# AVG
# df_clean <- df_clean %>%
  # mutate(Overall = rowMeans(select(., Gameplay, Story, Sociability, Scariness), na.rm = TRUE))

```

```{r H1}
model_h1_better <- glm(Sequel_Purchased ~ Overall, data = df_clean, family = binomial)
summary(model_h1_better)

```
```{r H2a-d}
model_h2 <- glm(Sequel_Purchased ~ Gameplay + Story + Sociability + Scariness,
                data = df_clean, family = binomial)
summary(model_h2)

```

```{r pscl}
# install.packages("pscl")
library(pscl)
pR2(model_full)  # McFadden R2 等指标

# 预测概率分布
df_clean$predicted <- predict(model_full, type = "response")

```


## Visualizing Model Results

```{r odds_ratio_plot_model_h1_better, message=FALSE, warning=FALSE, fig.cap="Odds Ratios with 95% CI for H1 (Overall Positivity)"}

tidy_model_h1_better <- broom::tidy(model_h1_better, conf.int = TRUE, exponentiate = TRUE)

ggplot(tidy_model_h1_better %>% filter(term != "(Intercept)"),
       aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_pointrange() +
  geom_hline(yintercept = 1, linetype = "dashed", color = "gray") +
  coord_flip() +
  labs(title = "Odds Ratios with 95% CI – H1 (Overall Positivity)",
       y = "Odds Ratio", x = "")
```

```{r odds_ratio_plot_model_h2, message=FALSE, warning=FALSE, fig.cap="Odds Ratios with 95% CI for H2a–H2d (Thematic Drivers)"}


tidy_model_h2 <- broom::tidy(model_h2, conf.int = TRUE, exponentiate = TRUE)

ggplot(tidy_model_h2 %>% filter(term != "(Intercept)"),
       aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_pointrange() +
  geom_hline(yintercept = 1, linetype = "dashed", color = "gray") +
  coord_flip() +
  labs(title = "Odds Ratios with 95% CI – H2a–H2d (Thematic Drivers)",
       y = "Odds Ratio", x = "")
```